### ISSUE TITLE
Password Reset Issue

### ISSUE THREAD

**Issue by digit-ex** [ryancramerdesign/LoginRegister#11]
The module allows configuration to login using email instead of username however when a user tries to reset their password, the reset form asks for username. If the user enters their email address no reset email is sent. In my case, user accounts were set up by me so users do not know their username, they have no need to know it since they log in with email so none can do a reset.

**Comment by ryancramerdesign** [comment]
LoginRegister uses the core ProcessForgotPassword module. The capability
was added in 3.0.103, and would just need to be enabled in that
ProcessForgotPassword module to utilize it with LoginRegister. It was added
to ProcessForgotPassword in part for the needs of LoginRegister. See here:
https://processwire.com/blog/posts/pw-3.0.103/#major-update-to-forgot-password-core-module

**Comment by digit-ex** [comment]
I'm running the latest stable version (3.0.98). I would rather leave the stable version in place since it's a live site, can I update just the forgot password module into the current pw install or do I have to upgrade the entire CMF to the dev version to get that working?

**Comment by ryancramerdesign** [comment]
I'm not sure about that. Usually you don't want to take modules from one
version and combine it with another, as that's not something that's planned
for or intended. It's always possible it would work in this instance, but I
don't know for sure. If this is a site you have in development, I would
suggest using the dev branch version rather than the master version. I
wouldn't describe the dev branch as unstable by any means. If history is
any guide, dev branch versions have often had stability benefits relative
to master branch versions, but of course that's not something that can be
guaranteed. You always want to test version upgrades thoroughly, whether
they originate from the master or dev branch.

**Comment by digit-ex** [comment]
I took the less potentially disruptive path of installing the latest dev. After configuring I ran a test and although the reset email took over 30 minutes to arrive, it did and the reset was completed. I'll mark this as closed. Thanks Ryan.
